runtime: nodejs
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.95
resources:
  cpu: 0.5
  memory_gb: 0.7
  disk_size_gb: 10